enum UserRole { ADMIN, ENABLER }
enum AssignmentStatus { PENDING, IN_PROGRESS, COMPLETED, SKIPPED }
enum CallOutcome { ANSWERED, BUSY, NO_RESPONSE, SWITCHED_OFF, WRONG_NUMBER, NOT_REACHABLE }
enum FollowUpStatus { NEW, CONTACTED, INTERESTED, NOT_INTERESTED, JOINED, PENDING, DORMANT }
enum EventStatus { ACTIVE, COMPLETED, CANCELLED }
enum QuestionType { DROPDOWN, TEXT, DATE, MULTI_SELECT, RADIO }
